[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["cargo", "derive"] }
colored = "3.1.1"
dirs = "6.0.0"
inquire = "0.9.3"
regex = "1.12.3"
rev_lines = "0.3.0"
termtree = "0.5.1"
walkdir = "2.5.0"
